name: flutter_photo_idea_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  blur: ^4.0.0
  d_info: ^0.2.0
  d_input: ^0.4.2
  d_session: ^0.0.3
  extended_image: ^9.0.7
  fd_log: ^0.0.8
  flutter:
    sdk: flutter
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  path: ^1.9.0
  sqflite: ^2.4.1
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
