name: flutter_photo_idea_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  fd_log: ^0.0.8
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_it: ^8.0.3
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
